{% set name = "pynvim" %}
{% set version = "0.4.2" %}
{% set sha256 = "6bc6204d465de5888a0c5e3e783fe01988b032e22ae87875912280bef0e40f8f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pytest-runner
    - pip
  run:
    - python
    - msgpack-python >=0.5.0
    - greenlet
    - trollius  # [py27]
    - pyuv >=1.0.0  # [win]

test:
  imports:
    - pynvim
    - pynvim.api
    - pynvim.msgpack_rpc
    - pynvim.msgpack_rpc.event_loop
    - pynvim.plugin

about:
  home: http://github.com/neovim/pynvim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client to neovim

  description: |
    Python client to neovim
  dev_url: https://github.com/neovim/pynvim

extra:
  recipe-maintainers:
    - curtisalexander
    - xhochy
